### PR TITLE
Update mpv.conf

### PR DESCRIPTION
**Pull request by ghost**
Add config that avoiding garbled.

### CODE REVIEW

**Comment by songchenwen** [comment]
What will happen if my subtitle is ascii encoded when I add this line?

**Comment by Acesx** [comment]
Uncertain but this is only the way to avoiding  the garbled when I always meet.

**Comment by songchenwen** [comment]
I usually use enca to transcode my none-utf8 subtitles.

**Comment by Acesx** [comment]
I found that.
Maybe I will try.

**Pull request closed without merging**
